platform :ios, '11.4'

target 'DataExample' do
  use_frameworks!

  pod 'BoseWearable', :path => 'BoseWearable-iOS-bin-4.0.8/'
  pod 'BLECore', :path => 'BoseWearable-iOS-bin-4.0.8/'
  pod 'Logging', :path => 'BoseWearable-iOS-bin-4.0.8/'
  
end
