platform :ios, '11.4'

target 'HeadingExample' do
  use_frameworks!

  pod 'BLECore', :path => '../../'
  pod 'BoseWearable', :path => '../../'
  pod 'Logging', :path => '../../'
  pod 'WorldMagneticModel', '~> 1.0'
end
